In [1]:
import numpy as np

In [2]:
# -- 1 --
    # 1. Создайте массив длины 10, заполненный нулями
    # 2. Сделайте полученный массив неизменяемым

zeros = np.zeros(10)
zeros.setflags(write=False)

In [3]:
# -- 2 --
    # 1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
    # 2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
    # 3. Составьте из полученных массивов координатную сеть (meshgrid)

range_2pi = np.linspace(0, 2 * np.pi, 5)
range_log = np.logspace(10, 100, 5)
xv, yv = np.meshgrid(range_2pi, range_log, indexing='ij')

In [4]:
# -- 3 --
    # Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

eye = np.diag(range(1, 5), k=-1)

In [106]:
# -- 4 --
    # 1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
    # 2. Создайте массив из построенного генератора
    
def my_iter():
    for i in range(9):
        yield i
    return

iter_arr = np.fromiter(my_iter(), dtype=int, count=9)

In [6]:
# -- 5 --
    # Что будет выведено на экран?
    # a = np.arange(4).reshape(2,2)  # dtype = int
    # a += 0.5                       # error : нельзя сменить dtype(a) на float (+= inplace)
    # print(a)                       

In [7]:
# -- 6 --
    # Что будет выведено на экран?
#     a = np.array([1])
#     if a:                          # ([1] == [True]) => [True]
#         print("True")
#     else:
#         print("False")

#     a = np.array([1, 2, 3])        # ([1, 2, 3] == [True, True, True]) =>  [True, False, False]
#     if a:                          # "if [True, False, False]" => error
#         print("True")
#     else:
#         print("False")

In [8]:
# -- 7 --
    # Что будет выведено на экран?   
    # print(0 * np.nan)                  # nan * number = nan
    # print(np.nan - np.nan)             # arithmetic_operation(nan, ...) = nan
    # print(np.nan == np.nan)            # False, т.к., например, не хотелось бы: nan - nan = 0, nan / nan = 1
    # print(np.nan is np.nan)            # True
    # print(-np.inf < np.nan < np.inf)   # х <> nan всегда False, т.к. nan не число

In [9]:
# -- 8 --
    # Что будет выведено на экран? 
    # print(np.isnan(np.array([np.nan]).astype(np.int)))    #False, т.к nan только для float dtype, a dtype=int заменит nan на число

In [10]:
np.array([np.NINF]).astype(np.uint64) # ???

array([9223372036854775808], dtype=uint64)

In [11]:
# -- 9 --
    # 1. Создайте масив из четырех элементов: 0, 10, 20, 30
    # 2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго, 
    # больше предыдущего элемента этой же строки на 1.
    
array = np.arange(0, 40, 10)
array.reshape((4, 1)) + np.arange(4)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [12]:
# -- 10 --
    # Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?
    
    # np.arange(5).reshape(1,-1) => строка (1, 5),
    # np.arange(5).reshape(-1,1) => столбец (5, 1),
    # + =>(broadcasting) (5, 5) 

In [13]:
# -- 11 --
    # Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке
    
chess_array = np.zeros((8,8))
mask = np.arange(0, 8, 2)
chess_array[mask, ::2] += 1
chess_array[mask + 1, 1::2] += 1
chess_array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [14]:
# -- 12 --
    # 1. Создайте одномерный массив целых чисел от 1 до 5
    # 2. Вставьте 0 между каждой парой соседних элементов
array = np.arange(1, 5)
result = np.zeros(7)
result[::2] = array
result

array([1., 0., 2., 0., 3., 0., 4.])

In [15]:
# -- 13 --
    # Что будет выведено на экран?
    # x = np.arange(36).reshape(2,3,2,3)
    # print(x[...,0,...])                 # error, "..." можно только 1 раз
                                          # (иначе неясно, до какого индекса ":")

In [16]:
# -- 14 --
    #Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]                 # y копирует 2,3 столбец х (advanced indexing)
y[:] = 0                       # 2, 3 столбец y в 0
print(x)                       # x без изменений
y = x[:,:2]                    # y сслылается на 0, 1 столбец x 
y[:] = 0                       # 0, 1 столбец x в 0
print(x)                       

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]]


In [17]:
# -- 15 --
# Замените отрицательные элементы массива нулем.
array = np.arange(-5, 5)
array[array < 0] = 0
array

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [18]:
# -- 16 --
    # На примере целочисленного массива
    # x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) 
    # составьте новый массив, не содержащий строки,
    # полностью заполненные одним уникальным значением.
    
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) 
first_elements = x[:, 0].reshape(4, 1)
x[np.any(x - first_elements, axis=1)]

array([[1, 2, 3],
       [2, 2, 1]])

In [19]:
# -- 17 --
    # Для заданного одномерного массива x выведите все элементы,
    # не превышающие своих соседей
    # (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

x = np.random.choice(10, 10)
print(x)
mask = np.ones_like(x, dtype=bool)
mask[:len(x) - 1] = x[:len(x) - 1] <= x[1::]
mask[1:] *= x[:len(x) - 1] >= x[1::]
x[mask]

[3 8 3 3 4 5 0 9 1 3]


array([3, 3, 3, 0, 1])

In [20]:
# -- 18 --
    # 1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
    # 2. Отсортируйте строки массива по возрастанию значения во втором столбце
    
array = np.random.choice(10, (3, 3))
print(array)
array[np.argsort(array[:, 1])]

[[8 1 4]
 [3 6 1]
 [2 3 2]]


array([[8, 1, 4],
       [2, 3, 2],
       [3, 6, 1]])

In [21]:
# -- 19 --
    # Поменяйте местами первую и вторую строки двумерного массива
    
array = np.arange(20).reshape(4, 5)
array[np.array([1,0, *range(2, len(array))])]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# -- 20 --
    # 1. Создайте массив 3x5, заполненный числами от 0 до 14
    # 2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива 

x = np.arange(15).reshape(3,5)
print(x)
y = x[np.ix_([0, 2], [1, 3])]       # ~ [[[0, 0], [2, 2]], [[1, 3], [1, 3]]]
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  3]
 [11 13]]


In [23]:
# -- 21 --
    # Что будет выведено на экран?
    
x = np.arange(5)       # x = [0, 1, 2, 3, 4]
x[[0,0,1]] = range(3)  # x[0] = 0, x[0] = 1, x[1] = 2
print(x)
x[[1,2,1]] += 1        # x[1] = 3, x[2] = 3, x[1] != 4 (inplace нельзя 2 раза(?))
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


In [24]:
# -- 22 --
    # Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный.
    # Какой из способов работает быстрее и почему?

array = np.arange(64).reshape((4, 4, 2, 2))
ravelled_array = array.ravel()               # view почти всегда, гарантия contigious; быстрее reshape, почему хз(
reshaped_array = array.reshape(-1)           # view, когда позволяют страйды, нет гарантии contigious
flattened_array = array.flatten()            # возвращает копию => медленно
ravelled_array.shape, reshaped_array.shape, flattened_array.shape

((64,), (64,), (64,))

In [25]:
# -- 23 --
    # 1. Создайте массив, заполненный случайными значениями
    # 2. Замените максимальные значения массива средним 

array = np.random.choice(6, 10)
print(array)
array[array == array.max()] = array.mean()
array

[1 3 3 3 2 5 5 5 3 0]


array([1, 3, 3, 3, 2, 3, 3, 3, 3, 0])

In [26]:
# -- 24 --
    # 1. Создайте двумерный массив 6x6, заполненный случайными значениями
    # 2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом
    
array = np.random.choice(range(1,10), (3, 3))
print(array)
array.sum(axis=1) / array.min(axis=0)


[[3 4 2]
 [3 6 8]
 [6 4 7]]


array([3.  , 4.25, 8.5 ])

In [27]:
# -- 25 --
    # 1. Создайте одномерный массив длины 10, заполненный случайными значениями
    # 2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1
    
array = np.random.choice(range(1, 20), 10)
print(array)
(array - array.min()) / (array.max()  - array.min())

[ 1  4 10  2  3 16 12  5 17 15]


array([0.    , 0.1875, 0.5625, 0.0625, 0.125 , 0.9375, 0.6875, 0.25  ,
       1.    , 0.875 ])

In [28]:
# -- 26 --
    # Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу
    
array = np.arange(20, dtype=float).reshape(4, 5)
array[::3] = np.nan
print(array)
np.nan_to_num(array, nan=np.nanmean(array, axis=0))


[[nan nan nan nan nan]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [nan nan nan nan nan]]


array([[ 7.5,  8.5,  9.5, 10.5, 11.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [ 7.5,  8.5,  9.5, 10.5, 11.5]])

In [29]:
# -- 27 --
    # Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями. 

array = np.arange(36).reshape(6, 6)
array[:, 1::4] = np.zeros((6, 2))
print(array)
np.any(array, axis=0)

[[ 0  0  2  3  4  0]
 [ 6  0  8  9 10  0]
 [12  0 14 15 16  0]
 [18  0 20 21 22  0]
 [24  0 26 27 28  0]
 [30  0 32 33 34  0]]


array([ True, False,  True,  True,  True, False])

In [30]:
# -- 28 --
    # 1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
    # 2. Вычислите суммы элементов по двум последним осям 

array = np.random.choice(10, (3, 4, 3, 4))
print(array)
print(array.sum(axis=(2, 3)))

[[[[7 1 3 2]
   [8 8 1 9]
   [4 6 2 5]]

  [[1 8 6 9]
   [5 4 8 8]
   [9 1 0 2]]

  [[7 0 7 3]
   [0 0 0 9]
   [3 3 9 1]]

  [[3 9 8 6]
   [3 1 4 5]
   [2 2 8 2]]]


 [[[2 7 4 8]
   [7 2 8 1]
   [5 5 6 2]]

  [[4 8 4 7]
   [6 2 2 4]
   [3 6 9 3]]

  [[9 4 0 0]
   [0 1 0 7]
   [3 4 0 1]]

  [[9 2 9 7]
   [1 6 0 7]
   [0 8 3 6]]]


 [[[9 5 7 1]
   [1 7 0 4]
   [3 7 9 8]]

  [[6 5 3 5]
   [5 0 0 1]
   [5 8 0 3]]

  [[9 8 7 9]
   [6 0 9 2]
   [5 5 8 6]]

  [[6 8 9 2]
   [1 6 4 3]
   [0 1 1 4]]]]
[[56 61 42 53]
 [57 58 29 58]
 [61 41 74 45]]


In [31]:
# -- 29 --
    # 1. Любым способом создайте два массива одинаковой длины
    # 2. Создайте массив, в котором на четных позициях будут стоять элементы
    # с соответствующих позиций первого массива, 
    # а на нечетных - с соответствующих позиций второго

x = np.arange(10)
y = np.arange(-10, 0)
array = np.zeros(len(x)*2)
array[::2] = x
array[1::2] = y
array

array([  0., -10.,   1.,  -9.,   2.,  -8.,   3.,  -7.,   4.,  -6.,   5.,
        -5.,   6.,  -4.,   7.,  -3.,   8.,  -2.,   9.,  -1.])

In [32]:
# -- 30 --
    # На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) 
    # вычислите долю пропущенных значений 
    
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.isnan(x).sum() / x.size

0.375

In [33]:
# -- 31 --
    # На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
    # составьте массив из уникальных значений массива без учета nan

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.unique(x[~np.isnan(x)])

array([1., 2., 3., 5.])

In [34]:
# -- 32 --
    # На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
    # найдите максимальный элемент в массиве среди элементов, 
    # перед которыми стоит нулевой 

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
next_zero_mask = np.clip(np.where(x == 0)[0] + 1, a_min=None, a_max=len(x) - 1)
x[next_zero_mask].max()

5

In [35]:
# -- 33 --
    # Пусть заданы два массива одинакового размера. 
    # Поэлементно разделите один массив на другой.
    # В случае, если делитель равен нулю, соответствующему элементу
    # результирующего массива присвойте нуль. 

nominator = np.random.choice(5, 7)
denominator = np.random.choice(5, 7)
denominator[:3] = 0
nominator / np.where(denominator != 0, denominator, np.inf)

array([0.        , 0.        , 0.        , 0.33333333, 4.        ,
       0.5       , 0.33333333])

In [36]:
# -- 34 --
    # Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]).
    # Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. 
    # В случае, если некоторый индекс встретился в массиве i несколько раз, 
    # прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
unique, counts =  np.unique(i, return_counts=True)
x[unique] += counts
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [37]:
# -- 35 --
    # По заданному массиву y = np.bincount([0, 0, 3, 8, 10, 10, 11]) 
    # постройте массив x такой, чтобы np.bincount(x) = y 

y = np.bincount([0, 0, 3, 8, 10, 10, 11])
print(y)
np.repeat(np.nonzero(y), y[y > 0])

[2 0 0 1 0 0 0 0 1 0 2 1]


array([ 0,  0,  3,  8, 10, 10, 11])

In [38]:
# -- 36 --
    # Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
    # Решите задачу на примере массива x = np.array([0,1,2,0,6,6,7,4,5,4])
    
x = np.array([0,1,2,0,6,6,7,4,5,4])
bins = np.bincount(x)
np.where(bins==bins.max())[0]

array([0, 4, 6])

In [39]:
# -- 37 --
    # Разбейте двумерный массив на список двумерных массивов 
    # по уникальным значениям в первом столбце.
    # Решите задачу на примере массива x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]),
    # в результате должен получиться список
    # [array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]. 
    
x = np.array([[1, 2], [1, 3],[5, 6], [7, 8], [5, 5], [2, 2], [3, 4], [3, 5]])
first_column = x[:, 0]
_, counts = np.unique(first_column, return_counts=True)
indexes = np.cumsum(counts)[:-1]
result = np.split(x[np.argsort(first_column)], indexes)
result

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]]),
 array([[5, 6],
        [5, 5]]),
 array([[7, 8]])]

In [40]:
# -- 38 --
    # По заданному одномерному массиву неотрицательных чисел постройте список подмассивов,
    # сожержащих элементы из полуинтервалов [i * 10, (i+1) * 10), i = 0, 1, 2, …
    # Решите задачу на примере массива x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]),
    # в результате должен получиться список [array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])].

x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])
sorted_x = np.sort(x)
blocks = np.arange(10, max(x), 10).reshape(-1, 1)
indexes = np.sum((sorted_x < blocks), axis=1)
np.split(sorted_x, indexes)

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

In [41]:
# -- 39 --
# Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?