In [420]:
import numpy as np

In [2]:
# -- 1 --
    # 1. Создайте массив длины 10, заполненный нулями
    # 2. Сделайте полученный массив неизменяемым

zeros = np.zeros(10)
zeros.setflags(write=False)

In [3]:
# -- 2 --
    # 1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
    # 2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
    # 3. Составьте из полученных массивов координатную сеть (meshgrid)

range_2pi = np.linspace(0, 2 * np.pi, 5)
range_log = np.logspace(10, 100, 5)
xv, yv = np.meshgrid(range_2pi, range_log, indexing='ij')

In [4]:
# -- 3 --
    # Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

eye = np.diag(range(1, 5), k=-1)

In [106]:
# -- 4 --
    # 1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
    # 2. Создайте массив из построенного генератора
    
def my_iter():
    for i in range(9):
        yield i
    return

iter_arr = np.fromiter(my_iter(), dtype=int, count=9)

In [6]:
# -- 5 --
    # Что будет выведено на экран?
    # a = np.arange(4).reshape(2,2)  # dtype = int
    # a += 0.5                       # error : нельзя сменить dtype(a) на float (+= inplace)
    # print(a)                       

In [7]:
# -- 6 --
    # Что будет выведено на экран?
#     a = np.array([1])
#     if a:                          # ([1] == [True]) => [True]
#         print("True")
#     else:
#         print("False")

#     a = np.array([1, 2, 3])        # ([1, 2, 3] == [True, True, True]) =>  [True, False, False]
#     if a:                          # "if [True, False, False]" => error
#         print("True")
#     else:
#         print("False")

In [8]:
# -- 7 --
    # Что будет выведено на экран?   
    # print(0 * np.nan)                  # nan * number = nan
    # print(np.nan - np.nan)             # arithmetic_operation(nan, ...) = nan
    # print(np.nan == np.nan)            # False, т.к., например, не хотелось бы: nan - nan = 0, nan / nan = 1
    # print(np.nan is np.nan)            # True
    # print(-np.inf < np.nan < np.inf)   # х <> nan всегда False, т.к. nan не число

In [9]:
# -- 8 --
    # Что будет выведено на экран? 
    # print(np.isnan(np.array([np.nan]).astype(np.int)))    #False, т.к nan только для float dtype, a dtype=int заменит nan на число

In [10]:
np.array([np.NINF]).astype(np.uint64) # ???

array([9223372036854775808], dtype=uint64)

In [161]:
# -- 9 --
    # 1. Создайте масив из четырех элементов: 0, 10, 20, 30
    # 2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго, 
    # больше предыдущего элемента этой же строки на 1.
    
array = np.arange(0, 40, 10)
array.reshape((4,1)) + np.arange(5)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [12]:
# -- 10 --
    # Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?
    
    # np.arange(5).reshape(1,-1) => строка (1, 5),
    # np.arange(5).reshape(-1,1) => столбец (5, 1),
    # + =>(broadcasting) (5, 5) 

In [169]:
# -- 11 --
    # Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке
    
chess_array = np.zeros((8,8))
mask = np.array([1, 3, 4, 7])
chess_array[mask,::2] = 1           # ::2, ::2
# chess_array[mask + 1, 1::2] += 1
chess_array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [14]:
# -- 12 --
    # 1. Создайте одномерный массив целых чисел от 1 до 5
    # 2. Вставьте 0 между каждой парой соседних элементов
array = np.arange(1, 5)
result = np.zeros(7)
result[::2] = array
result

array([1., 0., 2., 0., 3., 0., 4.])

In [15]:
# -- 13 --
    # Что будет выведено на экран?
    # x = np.arange(36).reshape(2,3,2,3)
    # print(x[...,0,...])                 # error, "..." можно только 1 раз
                                          # (иначе неясно, до какого индекса ":")

In [176]:
class Array:
    def __getitem__(self, x):
        print(type(x), x)

In [177]:
a = Array()
a[::2]

<class 'slice'> slice(None, None, 2)


In [ ]:
up_left = [10, 20]
bot_right = [100, 200]

sl_args in zip(up_left, bot_right)

In [ ]:
slice_ = slice(None) # !!

In [178]:
# -- 14 --
    # Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]                 # y копирует 2,3 столбец х (advanced indexing)
y[:] = 0                       # 2, 3 столбец y в 0
print(x)                       # x без изменений
y = x[:,:2]                    # y ссылается на 0, 1 столбец x 
y = 0                       # 0, 1 столбец x в 0
print(x)                       

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# -- 15 --
    # Замените отрицательные элементы массива нулем.
array = np.arange(-5, 5)
array[(array > -1) | (array < 2)] = 0
array

In [190]:
True is True == False # !!!!!!!!

False

In [ ]:
array > -1 or array < 2
(array < 2) or (array > -1)

In [ ]:
array > -1 | array < 2
x = -1 | array
(array > x) and (x < 2)

In [18]:
# -- 16 --
    # На примере целочисленного массива
    # x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) 
    # составьте новый массив, не содержащий строки,
    # полностью заполненные одним уникальным значением.
    
x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) 
first_elements = x[:, 0].reshape(4, 1)
x[np.any(x - first_elements, axis=1)]

array([[1, 2, 3],
       [2, 2, 1]])

In [240]:
# -- 17 --
    # Для заданного одномерного массива x выведите все элементы,
    # не превышающие своих соседей
    # (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

x = np.random.choice(10, 10)
print(x)
mask = np.ones_like(x, dtype=bool)  # empty
mask[:-1] = x[:-1] <= x[1::]
mask[1:] &= x[:-1] >= x[1::]
x[mask]

[8 2 2 5 4 8 7 9 5 9]


array([2, 2, 4, 7, 5])

In [210]:
# -- 18 --
    # 1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
    # 2. Отсортируйте строки массива по возрастанию значения во втором столбце
    
array = np.random.choice(10, (3, 3))
print(array)
array[np.argsort(array[:, 1])] # np lexsort

[[7 4 8]
 [0 8 8]
 [3 2 9]]


array([[3, 2, 9],
       [7, 4, 8],
       [0, 8, 8]])

In [202]:
# -- 19 --
    # Поменяйте местами первую и вторую строки двумерного массива
    
array = np.arange(20).reshape(4, 5)
array[[1,0, *range(2, len(array))]]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# -- 20 --
    # 1. Создайте массив 3x5, заполненный числами от 0 до 14
    # 2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива 

x = np.arange(15).reshape(3,5)
print(x)
y = x[np.ix_([0, 2], [1, 3])]       # ~ [[[0, 0], [2, 2]], [[1, 3], [1, 3]]]
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  3]
 [11 13]]


In [213]:
# -- 21 --
    # Что будет выведено на экран?
    
x = np.arange(5)       # x = [0, 1, 2, 3, 4]
x[[0,0,1]] = range(3)  # x[0] = 0, x[0] = 1, x[1] = 2
print(x)
x[[1,2,1]] += 1        # x[1] = 3, x[2] = 3, x[1] != 4,     y.__iadd__(1)
print(x)               # (x[[...]] - копия, shape: (3,))    np.add.at(x, [1, 2, 1], 1)

[1 2 2 3 4]
[1 3 3 3 4]


In [24]:
# -- 22 --
    # Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный.
    # Какой из способов работает быстрее и почему?

array = np.arange(64).reshape((4, 4, 2, 2))
ravelled_array = array.ravel()               # view почти всегда, гарантия contigious; быстрее reshape
reshaped_array = array.reshape(-1)           # view, когда позволяют страйды, нет гарантии contigious
flattened_array = array.flatten()            # возвращает копию => медленно
# x.shape = (...) упадет если mismatch
ravelled_array.shape, reshaped_array.shape, flattened_array.shape

((64,), (64,), (64,))

In [25]:
# -- 23 --
    # 1. Создайте массив, заполненный случайными значениями
    # 2. Замените максимальные значения массива средним 

array = np.random.choice(6, 10)
print(array)
array[array == array.max()] = array.mean() # argmax, numba, np.place, np.put <- %%timeit
array

[1 3 3 3 2 5 5 5 3 0]


array([1, 3, 3, 3, 2, 3, 3, 3, 3, 0])

In [26]:
# -- 24 --
    # 1. Создайте двумерный массив 6x6, заполненный случайными значениями
    # 2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом
    
array = np.random.choice(range(1,10), (3, 3))
print(array)
array.sum(axis=1) / array.min(axis=0)


[[3 4 2]
 [3 6 8]
 [6 4 7]]


array([3.  , 4.25, 8.5 ])

In [27]:
# -- 25 --
    # 1. Создайте одномерный массив длины 10, заполненный случайными значениями
    # 2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1
    
array = np.random.choice(range(1, 20), 10)
print(array)
(array - array.min()) / (array.max()  - array.min()) # проходов по массиву много, np.ptp(тоже 2 прохода)

[ 1  4 10  2  3 16 12  5 17 15]


array([0.    , 0.1875, 0.5625, 0.0625, 0.125 , 0.9375, 0.6875, 0.25  ,
       1.    , 0.875 ])

In [28]:
# -- 26 --
    # Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу
    
array = np.arange(20, dtype=float).reshape(4, 5)
array[::3] = np.nan
print(array)
np.nan_to_num(array, nan=np.nanmean(array, axis=0))   # np.nonzero(np.isnan(x)) ~ where(...)[0]

[[nan nan nan nan nan]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [nan nan nan nan nan]]


array([[ 7.5,  8.5,  9.5, 10.5, 11.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [ 7.5,  8.5,  9.5, 10.5, 11.5]])

In [10]:
# -- 27 --
    # Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями. 

array = np.arange(36).reshape(6, 6)
array[:, 1::4] = np.zeros((6, 2))
print(array)
~np.any(array, axis=0) 

[[ 0  0  2  3  4  0]
 [ 6  0  8  9 10  0]
 [12  0 14 15 16  0]
 [18  0 20 21 22  0]
 [24  0 26 27 28  0]
 [30  0 32 33 34  0]]


array([False,  True, False, False, False,  True])

In [199]:
array = np.empty((300, 300))
array[:, 1::4] = np.zeros((300, 1))
array = array.astype(bool)

In [200]:
%%timeit 
~np.any(array, axis=0)

13.2 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [203]:
%%timeit
np.all(~array, axis=0)

15.7 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [167]:
# -- 28 --
    # 1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
    # 2. Вычислите суммы элементов по двум последним осям 

array = np.random.choice(10, (3, 4, 3, 4))
print(array)
print(array.sum(axis=(2, 3)))    # https://en.wikipedia.org/wiki/Pairwise_summation 

[[[[1 1 2 0]
   [7 0 1 1]
   [5 4 1 0]]

  [[4 5 8 6]
   [2 4 0 9]
   [5 7 5 8]]

  [[6 7 7 9]
   [0 7 3 8]
   [8 0 4 3]]

  [[2 0 5 3]
   [5 7 9 2]
   [6 6 1 9]]]


 [[[5 8 6 1]
   [2 3 2 5]
   [5 7 1 5]]

  [[6 4 5 4]
   [8 8 2 5]
   [6 3 0 0]]

  [[6 7 2 9]
   [7 7 8 6]
   [6 3 9 9]]

  [[0 5 5 6]
   [0 6 3 0]
   [5 0 3 4]]]


 [[[8 0 3 1]
   [6 5 2 6]
   [1 4 4 2]]

  [[2 3 5 2]
   [4 6 2 0]
   [8 7 0 2]]

  [[0 9 7 1]
   [1 5 2 4]
   [6 0 1 0]]

  [[1 1 2 0]
   [5 7 2 5]
   [1 8 5 9]]]]
[[23 63 62 55]
 [50 51 79 37]
 [42 41 36 46]]


In [168]:
np.add.reduce(array, axis=(2,3))

array([[23, 63, 62, 55],
       [50, 51, 79, 37],
       [42, 41, 36, 46]])

In [204]:
array = np.random.choice(100, (1000, 4, 5, 4))

In [205]:
%%timeit 
np.add.reduce(array, axis=(2,3))

71.8 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [206]:
%%timeit 
array.sum(axis=(2,3))

72.3 µs ± 967 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [142]:
# -- 29 --
    # 1. Любым способом создайте два массива одинаковой длины
    # 2. Создайте массив, в котором на четных позициях будут стоять элементы
    # с соответствующих позиций первого массива, 
    # а на нечетных - с соответствующих позиций второго

x = np.arange(10)
y = np.arange(-10, 0)
np.insert(y, slice(10), x) 

array([  0, -10,   1,  -9,   2,  -8,   3,  -7,   4,  -6,   5,  -5,   6,
        -4,   7,  -3,   8,  -2,   9,  -1])

In [210]:
x = np.arange(1000)
y = np.arange(-1000, 0)
ar = np.arange(1000)

In [211]:
%%timeit 
np.insert(y, ar, x) 

32.6 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [156]:
%%timeit 
z = np.zeros(1000)
z[::2] = x[::2]
z[1::2] = y[1::2]

2.24 µs ± 66.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
# -- 30 --
    # На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) 
    # вычислите долю пропущенных значений 
    
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.isnan(x).sum() / x.size

0.375

In [212]:
x = np.empty((300, 300))
x[::3, ::2] = np.nan

In [28]:
%%timeit 
np.isnan(x).sum() / x.size

117 µs ± 1.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [213]:
%%timeit # !!!!!!!!!!
np.isnan(x).mean()

98.1 µs ± 861 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
%%timeit 
np.isnan(x).sum() / np.prod(x.shape)

123 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
# -- 31 --
    # На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
    # составьте массив из уникальных значений массива без учета nan

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.unique(x[~np.isnan(x)])

array([1., 2., 3., 5.])

In [214]:
# -- 32 --
    # На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
    # найдите максимальный элемент в массиве среди элементов, 
    # перед которыми стоит нулевой 

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
mask = np.argwhere(x[:-1] == 0) + 1
# mask = mask[mask < len(x)]
x[mask].max()

5

In [215]:
x = np.empty(1000)
x[::5] = 0

In [216]:
%%timeit 
mask = np.argwhere(x[:-1] == 0) + 1
# mask = mask[mask < len(x)]
x[mask].max()

11.4 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [217]:
%%timeit 
np.max(x[np.r_[False, x==0][:-1]])

15.2 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [43]:
%%timeit 
np.max(x[1:][x[1:] == np.diff(x)])

10.7 µs ± 147 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
# -- 33 --
    # Пусть заданы два массива одинакового размера. 
    # Поэлементно разделите один массив на другой.
    # В случае, если делитель равен нулю, соответствующему элементу
    # результирующего массива присвойте нуль. 

nominator = np.random.choice(5, 7)
denominator = np.random.choice(5, 7)
denominator[:3] = 0
nominator / np.where(denominator != 0, denominator, np.inf)

array([0. , 0. , 0. , 2. , 0. , 1.5, 0. ])

In [223]:
nominator = np.random.choice(5, 300)
denominator = np.random.choice(5, 300)
denominator[::10] = 0

In [225]:
%%timeit
np.where(denominator != 0, nominator / denominator, 0)

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in true_divide
<magic-timeit>:1: RuntimeWarning: invalid value encountered in true_divide


5.77 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [227]:
%%timeit
res = np.divide(nominator, denominator)
np.nan_to_num(res, copy=False)

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in true_divide
<magic-timeit>:1: RuntimeWarning: invalid value encountered in true_divide


20.3 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [228]:
%%timeit
res = np.divide(nominator, denominator)
res[denominator == 0] = 0

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in true_divide
<magic-timeit>:1: RuntimeWarning: invalid value encountered in true_divide


4.67 µs ± 76.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
%%timeit 
nominator / np.where(denominator != 0, denominator, np.inf)

3.74 µs ± 98.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [221]:
nominator = np.random.choice(5, 300).astype(float)
denominator = np.random.choice(5, 300).astype(float)
denominator[::10] = 0.

In [54]:
%%timeit 
np.divide(nominator, denominator, out=np.zeros_like(nominator), where=denominator!=0)

6.94 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
# -- 34 --
    # Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]).
    # Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. 
    # В случае, если некоторый индекс встретился в массиве i несколько раз, 
    # прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
unique, counts =  np.unique(i, return_counts=True)
x[unique] += counts
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [73]:
x = np.ones(300)
i = np.random.choice(300, 20)
i = i.repeat(2)
j = np.random.choice(300, 40)
i = np.hstack([i, j])
np.random.shuffle(i)

In [71]:
%%timeit 
unique, counts =  np.unique(i, return_counts=True)
x[unique] += counts

14.8 µs ± 176 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
%%timeit 
x + np.bincount(i, minlength=len(x))

2.34 µs ± 60 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [78]:
# -- 35 --
    # По заданному массиву y = np.bincount([0, 0, 3, 8, 10, 10, 11]) 
    # постройте массив x такой, чтобы np.bincount(x) = y 

y = np.bincount([0, 0, 3, 8, 10, 10, 11])
print(y)
np.repeat(np.nonzero(y), y[y > 0])

[2 0 0 1 0 0 0 0 1 0 2 1]


array([ 0,  0,  3,  8, 10, 10, 11])

In [84]:
y = np.bincount(np.random.choice(30, 300))

In [85]:
%%timeit 
np.repeat(np.nonzero(y), y[y > 0])

6.72 µs ± 88.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [86]:
%%timeit
np.repeat(np.arange(y.size), y)

2.54 µs ± 35.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
# -- 36 --
    # Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
    # Решите задачу на примере массива x = np.array([0,1,2,0,6,6,7,4,5,4])
    
x = np.array([0,1,2,0,6,6,7,4,5,4])
bins = np.bincount(x)
np.argwhere(bins==bins.max()).ravel()

array([0, 4, 6])

In [229]:
x = np.random.choice(20, 300)

In [230]:
%%timeit 
bins = np.bincount(x)
np.argwhere(bins==bins.max())

9.55 µs ± 194 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [91]:
%%timeit 
unique, count = np.unique(x, return_counts=True)
unique[count == count.max()]

19 µs ± 491 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [98]:
# -- 37 --
    # Разбейте двумерный массив на список двумерных массивов 
    # по уникальным значениям в первом столбце.
    # Решите задачу на примере массива x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]),
    # в результате должен получиться список
    # [array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]. 
    
x = np.array([[1, 2], [1, 3],[5, 6], [7, 8], [5, 5], [2, 2], [3, 4], [3, 5]])
first_column = x[:, 0]
_, counts = np.unique(first_column, return_counts=True)
indexes = np.cumsum(counts)[:-1]
result = np.split(x[np.argsort(first_column)], indexes)
result

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]]),
 array([[5, 6],
        [5, 5]]),
 array([[7, 8]])]

In [93]:
x = np.random.choice(20, 200).reshape((100, 2))

In [94]:
%%timeit
first_column = x[:, 0]
_, counts = np.unique(first_column, return_counts=True)
indexes = np.cumsum(counts)[:-1]
result = np.split(x[np.argsort(first_column)], indexes)

54.4 µs ± 972 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [235]:
x = np.array([[1, 2],[3, 4], [3, 5], [4, 4], [5, 5]])
np.array_split(x, len(np.unique(x[:, 0])))

[array([[1, 2],
        [3, 4]]),
 array([[3, 5]]),
 array([[4, 4]]),
 array([[5, 5]])]

In [95]:
%%timeit 
np.array_split(x, len(np.unique(x[:, 0])))

37.2 µs ± 795 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [589]:
# -- 38 --
    # По заданному одномерному массиву неотрицательных чисел постройте список подмассивов,
    # сожержащих элементы из полуинтервалов [i * 10, (i+1) * 10), i = 0, 1, 2, …
    # Решите задачу на примере массива x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]),
    # в результате должен получиться список [array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])].

x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20, 88])
sorted_x = np.sort(x)
blocks = np.arange(10, max(x), 10)
# indexes = np.sum((sorted_x < blocks), axis=1) # для кажд блока индекс последнего вхождения
indexes = np.searchsorted(sorted_x, blocks)
np.split(sorted_x, indexes)

[array([0, 2, 2, 8]),
 array([10, 11, 13, 18]),
 array([20, 24]),
 array([34]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([88])]

In [41]:
# -- 39 --
# Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. 
# Какой из способов работает быстрее?

# 1. np.concatenate(axis=0)
 # ~ concatenate(): 
    # 2. np.vstack 
    # 3. np.hstack(x.T, y.T).T 
    # 4. np.append(x, y, axis=0)  

    # 5. np.stack((*x, *y), axis=0)   * очень медленно, но нужны одинаковые shapes
    # 6. np.row_stack([x, y])
    # 7. np.column_stack((x.T, y.T)).T
    # 8. np.block([x.T, y.T]).T

In [338]:
x = np.arange(10000).reshape((200, 50))
y = np.arange(10000, 25000).reshape((300, 50))

In [306]:
%%timeit
np.concatenate([x, y], axis=0)

7.69 µs ± 326 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [307]:
%%timeit
np.vstack([x, y])

14.4 µs ± 3.81 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [308]:
%%timeit
np.hstack([x.T, y.T]).T

16.6 µs ± 3.46 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [309]:
%%timeit
np.append(x, y, axis=0)

11.2 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [310]:
%%timeit
np.stack((*x, *y), axis=0)

776 µs ± 87.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [339]:
%%timeit
np.row_stack([x, y])

8.78 µs ± 527 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [316]:
%%timeit
np.column_stack((x.T, y.T)).T

10.3 µs ± 570 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [312]:
%%timeit
np.block([x.T, y.T]).T

20.6 µs ± 3.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# -- 40 --
    # Для двух одномерных массивов x = np.arange(3) и y = np.arange(5) 
    # постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

x = np.arange(3) 
y = np.arange(5) 
x = x.repeat(5)
y = np.tile(y, 3) # meshgrid !
np.stack([x, y], axis=0).reshape(-1, 2)

In [584]:
x = np.arange(3) 
y = np.arange(5)
np.array(np.meshgrid(x, y)).T.reshape(-1, 2)

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]])

In [333]:
# -- 41 --
    # По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
    # Решите задачу на примере массивов x = np.array([1,2,3,4]) и y = np.array([5,6,7,8])

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

np.column_stack([x, y]) # 1 

np.concatenate([x.reshape(-1, 1), y.reshape(-1, 1)], axis=1) # 2

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [350]:
# -- 42 --
    # По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив
    # в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив 
    # полностью заполненный нулями.
    # Решите задачу для списка l = [np.array([[1, 2], [3, 4]]), 
    # np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]
    
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]
res = np.zeros((2 * len(l) - 1, *l[0].shape))
res[::2] = l
res

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 9., 10.],
        [11., 12.]]])

In [356]:
# -- 43 -- 
    # Преобразуйте одномерный массив x = np.array([3,7,2,5,0,9,8,2,4,5]) в двумерный массив,
    # первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.
    
x = np.array([3,7,2,5,0,9,8,2,4,5])
np.lib.stride_tricks.as_strided(x, strides=(8, 8), shape=(6, 5))

array([[3, 7, 2, 5, 0],
       [7, 2, 5, 0, 9],
       [2, 5, 0, 9, 8],
       [5, 0, 9, 8, 2],
       [0, 9, 8, 2, 4],
       [9, 8, 2, 4, 5]])

In [593]:
# -- 44 --
    # Для заданного двумерного массива постройте трехмерный массив,
    # содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла.
    # Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
    # Решите задачу на примере массива x = np.arange(49).reshape(7,7)
    
x = np.arange(49).reshape(7, 7)
print(x)
n_rows, n_cols = (x.shape[0] // 3) * 3, (x.shape[1] // 3) * 3
x = x[:n_rows, :n_cols].copy()                      # .copy чтобы сменить страйды
x = x.reshape((n_rows // 3, 3, n_cols))             # n_rows // 3 = k блоков высоты 3, длины n_cols
# каждый из k блоков делим на n_cols // 3 блоков 3x3  
x = np.lib.stride_tricks.as_strided(x, strides=(n_cols * 3 * 8, 8 * 3, n_cols * 8, 8), shape=(n_rows // 3, n_cols // 3, 3, 3))
x.reshape(4, 3, 3)                                  # убираем размерность 0

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]],

       [[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

In [429]:
import numpy.ma as ma

In [442]:
# -- 45 -- 
    # Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
    # Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.
    
x = np.zeros(20)
x[0] = 100
mx = ma.masked_greater(x, x.std() + 3)
mx, mx.std()

(masked_array(data=[--, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              mask=[ True, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=1e+20),
 0.0)

In [513]:
# -- 46 -- 
    # Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
    # Решите задачу на примере массива x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]]).
    
x = ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])
col_mask = np.broadcast_to(np.all(x.mask, axis=0), x.data.shape)
x = ma.masked_where(col_mask, x.data)
ma.compress_rowcols(x, axis=1)

array([[1, 3],
       [4, 6]])

In [576]:
# -- 47 -- 
    # Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
    # Решите задачу на примере массива x = np.arange(25).reshape(5, 5).
    
x = np.arange(25).reshape(5, 5)
mx = ma.array(x)
mx[:, [mx.argmin(axis=1), mx.argmax(axis=1)]] = ma.masked
mx

masked_array(
  data=[[--, 1, 2, 3, --],
        [--, 6, 7, 8, --],
        [--, 11, 12, 13, --],
        [--, 16, 17, 18, --],
        [--, 21, 22, 23, --]],
  mask=[[ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True]],
  fill_value=999999)

In [626]:
# -- 48 -- 
    # Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: 
    # i-е значение результирующего массива вычисляется как медиана подмассива a[i - (k-1)/2: i - (k-1)/2 + 1].
    # В случае если границы окна выходят за границы массива, 
    # дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
    # Решите задачу на примере массива a = np.array([3, 8, 100, -3, -7, 4, 0, 2]) и ширины окна k = 5.
    
a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
k = 5
m = (k - 1) // 2
a_new = np.empty(k - 1 + len(a), dtype=a.dtype)
a_new[:m] = a[0]
a_new[m: len(a_new) - m] = a
a_new[-1: -m - 1: -1] = a[-1]
# 1
a_strided = np.lib.stride_tricks.as_strided(a_new, shape=(len(a), k), strides=(8, 8))
print(a_strided)
np.median(a_strided, axis=1)

[[  3   3   3   8 100]
 [  3   3   8 100  -3]
 [  3   8 100  -3  -7]
 [  8 100  -3  -7   4]
 [100  -3  -7   4   0]
 [ -3  -7   4   0   2]
 [ -7   4   0   2   2]
 [  4   0   2   2   2]]


array([3., 3., 3., 4., 0., 0., 2., 2.])

In [635]:
# 2
res = np.empty(dtype=a.dtype, shape=a.shape)
for i in range(m, len(a) + m):
    res[i - m] = np.median(a_new[i - m: i + m + 1])
res

array([3, 3, 3, 4, 0, 0, 2, 2])

In [644]:
a = np.empty(10000, dtype=int)
k = 5
m = (k - 1) // 2
a_new = np.empty(k - 1 + len(a), dtype=a.dtype)
a_new[:m] = a[0]
a_new[m: len(a_new) - m] = a
a_new[-1: -m - 1: -1] = a[-1]

In [645]:
%%timeit 
a_strided = np.lib.stride_tricks.as_strided(a_new, shape=(len(a), k), strides=(8, 8))
np.median(a_strided, axis=1)

370 µs ± 2.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [646]:
%%timeit 
res = np.empty(dtype=a.dtype, shape=a.shape)
for i in range(m, len(a) + m):
    res[i - m] = np.median(a_new[i - m: i + m + 1])

180 ms ± 567 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [667]:
# -- 49 --
    # По заданному массиву a размера Nx2 постройте одномерный массив длины N,
    # i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца,
    # индекс которого содержится в i-й строке второго столбца. 
    # В случае, если во втором столбце массива a содержится индекс, выходящий за границы, 
    # к элементу первого столбца ничего не прибавляйте.
    # Решите задачу на примере массива a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]]).
    

a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])
res = a[:, 0].copy()
# 1
for i in range(len(a)):
    idx = a[i, 1]
    add = a[idx, 0] if idx < len(a) else 0
    res[i] += add 
res

array([13,  6, 16,  9, 12])

In [706]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])
res = a[:, 0].copy()
# 2
indexes = a[:, 1] 
add = np.zeros(len(a), dtype=a.dtype)
add[indexes < len(a)] = a[indexes[indexes < len(a)], 0]
res += add
res

array([13,  6, 16,  9, 12])

In [714]:
a = np.empty((1000, 2), dtype=int)

In [717]:
%%timeit 
res = a[:, 0].copy()
for i in range(len(a)):
    idx = a[i, 1]
    add = a[idx, 0] if idx < len(a) else 0
    res[i] += add 

528 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [718]:
%%timeit
res = a[:, 0].copy()
indexes = a[:, 1] 
add = np.zeros(len(a), dtype=a.dtype)
add[indexes < len(a)] = a[indexes[indexes < len(a)], 0]
res += add

8.71 µs ± 218 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [781]:
# -- 50 -- 
    # По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей,
    # параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива,
    # лежащих на соответствующих диагоналях.
    # Решите задачу на примере массива a = np.arange(16).reshape(4, 4), в результате должен получиться словарь
    # {0: [0],
    #  1: [1, 4],
    #  2: [2, 5, 8],
    #  3: [3, 6, 9, 12],
    #  4: [7, 10, 13],
    #  5: [11, 14],
    #  6: [15]}.

a = np.arange(16).reshape(4, 4)
print(a)
# 1
num_diag = a.shape[1] + a.shape[0] - 1
res = {i: [] for i in range(num_diag)}
for i in range(a.shape[1]):
    for k, j in zip(range(i + 1), range(i, -1, -1)):
        res[i].append(a[k, j])
        if i != num_diag // 2:
            res[num_diag - i - 1].insert(0, a[len(a) - k - 1, a.shape[1] - j - 1])
res

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}

In [782]:
# 2
a_rotated = np.fliplr(a)
res = {a.shape[1] - i - 1: a_rotated.diagonal(i) for i in range(-a.shape[1] + 1, a.shape[1])}
res

{6: array([15]),
 5: array([11, 14]),
 4: array([ 7, 10, 13]),
 3: array([ 3,  6,  9, 12]),
 2: array([2, 5, 8]),
 1: array([1, 4]),
 0: array([0])}

In [783]:
a = np.arange(1024).reshape(32, 32)

In [784]:
%%timeit
num_diag = a.shape[1] + a.shape[0] - 1
res = {i: [] for i in range(num_diag)}
for i in range(a.shape[1]):
    for k, j in zip(range(i + 1), range(i, -1, -1)):
        res[i].append(a[k, j])
        if i != num_diag // 2:
            res[num_diag - i - 1].insert(0, a[len(a) - k - 1, a.shape[1] - j - 1])

365 µs ± 3.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [785]:
%%timeit
a_rotated = np.fliplr(a)
res = {a.shape[1] - i - 1: a_rotated.diagonal(i) for i in range(-a.shape[1] + 1, a.shape[1])}

25.1 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
