In [1]:
%load_ext autoreload

In [2]:
import torch 
import numpy as np

from pixel_shuffle import pixel_shuffle, pixel_unshuffle

%autoreload 2

In [14]:
# sanity check 
inputs = torch.randn(1, 64, 2, 3, 6)
factor = 4

In [15]:
print('inputs shape: ', inputs.size())
shuffled = pixel_shuffle(inputs, factor)
print('shuffled shape: ', shuffled.size())
unshuffled = pixel_unshuffle(shuffled, factor)
print('unshuffled shape: ', unshuffled.size())

assert np.all(unshuffled.numpy() == inputs.numpy())

inputs shape:  torch.Size([1, 64, 2, 3, 6])
shuffled shape:  torch.Size([1, 1, 8, 12, 24])
unshuffled shape:  torch.Size([1, 64, 2, 3, 6])


In [ ]:
# torch test 
inputs = torch.randn(1, 64, 2, 3)
factor = 4

In [12]:
shuffled = pixel_shuffle(inputs, factor)
unshuffled = pixel_unshuffle(shuffled, factor)

torch_shuffled = torch.nn.functional.pixel_shuffle(inputs, factor)
torch_unshuffled = torch.nn.functional.pixel_unshuffle(torch_shuffled, factor)

assert np.all(unshuffled.numpy() == torch_unshuffled.numpy()) 

(torch.Size([1, 4, 8, 12]), torch.Size([1, 64, 2, 3]))

In [20]:
# reshape test 
inputs = torch.randn(1, 4, 2)
reshaped = inputs.reshape(1, 1, 8)
shuffled = pixel_shuffle(inputs, 4)

assert reshaped.shape == shuffled.shape
assert np.all(reshaped.numpy() == shuffled.numpy())

AssertionError: 

In [27]:
inputs = torch.ones(1, 4, 2, 2)
inputs[:, 0, :] = 0
inputs[:, 1, :] = 1
inputs[:, 2, :] = 2
inputs[:, 3, :] = 3
print('input:\n ', inputs[0])
print('reshape:\n ', inputs.reshape(1, 1, 4, 4)[0])
print('shuffle:\n ', pixel_shuffle(inputs, 2)[0])

input:
  tensor([[[0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])
reshape:
  tensor([[[0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])
shuffle:
  tensor([[[0., 1., 0., 1.],
         [2., 3., 2., 3.],
         [0., 1., 0., 1.],
         [2., 3., 2., 3.]]])
